spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource #使用hikari连接池
    driver-class-name: org.h2.Driver #数据库驱动
    url: jdbc:h2:file:~/.h2/tb_user;Auto_Server=True;IgnoreCase=True;Mode=MySql  #h2数据库的连接地址
    username: root #用户名
    password: root #密码
    name: tb_user
    schema: classpath:sql/schema.sql #数据库结构
    data: classpath:sql/init.sql #初始化数据库数据
    hikari:
      connection-test-query: select 'x'
      minimum-idle: 1
      maximum-pool-size: 10
      idle-timeout: 60000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        useLocalTransactionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false #是否允许远程访问
logging:
  level:
    com.xub.jpa.dao: debug